language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      # osx_image: xcode7.2

# dist: xenial

# os:
  # - linux
  # - osx

# compiler:
#   - gcc
#   - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

# additional linux dependencies
addons:
  apt:
    packages:
      - libboost-program-options-dev
      - libyaml-cpp-dev

# additional mac dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yaml-cpp; fi

script: make
