agentTypes:
  - type: ground
    roadmap: "roadmap.yaml"
    v_max: 0.5 # m/s
    a_max: 2.0 # m/s^2
    shape:
      type: cylinder
      radius: 0.2 # m
      height: 0.45 # m
agentInteractions:
  - typeA: ground
    typeB: ground
    above: 0.45
    below: 0.45
    radius: 0.4
